easy_admin:
    site_name: Espace Admin
    entities:
       - App\Entity\Product
       - App\Entity\Category
       - App\Entity\User
    user:
          name_property_path: 'email'
          display_avatar: true